### ISSUE TITLE
addData throws error?

### ISSUE THREAD

**Issue by mogmios** [gpit2286/mailgun-es6#5]
It seems to make more sense in formdata.js addData() if instead of throwing an error when value is undefined it instead just ignores that attribute as if it were not there at all. That would seem to make it easier to programmatically construct options..

{
opt = arg || undefined;
}

**Comment by gpit2286** [comment]
I don't understand.  The addData function doesn't work with an object at all.  

The reason I required the value is because I don't know if the MG servers would freak out if there was not value and then all of a sudden a new boundary.  If you can make a good use case, I'll test it out.  For now, I'm just going to let it be.
